"use client";

import type { Alert } from "@/lib/api";
import type { Lang } from "@/lib/i18n";

const SEVERITY_STYLE: Record<Alert["severity"], {
  border: string; bg: string; icon: string; iconColor: string; label: string;
}> = {
  high:     { border: "border-red-500/40",     bg: "bg-red-500/5",     icon: "▲", iconColor: "text-red-400",    label: "URGENTE" },
  medium:   { border: "border-amber-500/40",   bg: "bg-amber-500/5",   icon: "●", iconColor: "text-amber-300",  label: "AVISO"   },
  low:      { border: "border-zinc-700",       bg: "bg-zinc-900/40",   icon: "·", iconColor: "text-zinc-400",   label: "INFO"    },
  positive: { border: "border-emerald-500/40", bg: "bg-emerald-500/5", icon: "▲", iconColor: "text-emerald-300", label: "BUENO"  },
};

const SEVERITY_STYLE_EN = {
  high: "URGENT", medium: "WATCH", low: "INFO", positive: "GOOD",
};

const TYPE_LABEL: Record<Alert["type"], { es: string; en: string }> = {
  agent_trend:      { es: "Agente",     en: "Agent"   },
  lead_source:      { es: "Fuente",     en: "Source"  },
  forecast:         { es: "Pronóstico", en: "Forecast"},
  contact_velocity: { es: "Velocidad",  en: "Velocity"},
  campaign:         { es: "Campaña",    en: "Campaign"},
  dialer:           { es: "Marcador",   en: "Dialer"  },
};

export default function AlertsTab({ lang, alerts }: { lang: Lang; alerts: Alert[] }) {
  const sortOrder: Record<Alert["severity"], number> = { high: 0, medium: 1, positive: 2, low: 3 };
  const sorted = [...alerts].sort((a, b) => sortOrder[a.severity] - sortOrder[b.severity]);

  const counts = {
    high: alerts.filter(a => a.severity === "high").length,
    medium: alerts.filter(a => a.severity === "medium").length,
    positive: alerts.filter(a => a.severity === "positive").length,
  };

  return (
    <section className="space-y-4">
      <div className="flex items-end justify-between">
        <div>
          <h2 className="text-lg font-medium">{lang === "es" ? "Alertas" : "Alerts"}</h2>
          <p className="text-sm text-zinc-400">
            {lang === "es"
              ? `${alerts.length} alertas generadas por IA basadas en datos de la última semana`
              : `${alerts.length} alerts generated by AI from last week's data`}
          </p>
        </div>
        <div className="flex gap-2 text-xs">
          <Counter color="red"     value={counts.high}     label={lang === "es" ? "urgentes" : "urgent"} />
          <Counter color="amber"   value={counts.medium}   label={lang === "es" ? "avisos"   : "watch"}  />
          <Counter color="emerald" value={counts.positive} label={lang === "es" ? "buenos"   : "good"}   />
        </div>
      </div>

      {sorted.length === 0 ? (
        <div className="rounded-lg border border-zinc-800 p-8 text-center text-zinc-500 text-sm">
          {lang === "es" ? "Sin alertas. Todo en orden." : "No alerts. All clear."}
        </div>
      ) : (
        <div className="space-y-3">
          {sorted.map((a, i) => {
            const s = SEVERITY_STYLE[a.severity];
            const sevLabel = lang === "en" ? SEVERITY_STYLE_EN[a.severity] : s.label;
            return (
              <div key={i} className={`rounded-lg border ${s.border} ${s.bg} p-4`}>
                <div className="flex items-start gap-3">
                  <span className={`text-lg leading-none mt-0.5 ${s.iconColor}`}>{s.icon}</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span className={`text-[10px] font-semibold tracking-wider ${s.iconColor}`}>
                        {sevLabel}
                      </span>
                      <span className="text-[10px] uppercase tracking-wider text-zinc-500 border border-zinc-700 px-1.5 py-px rounded">
                        {TYPE_LABEL[a.type]?.[lang] ?? a.type}
                      </span>
                    </div>
                    <h3 className="font-medium text-zinc-100 mb-1">{a.title}</h3>
                    <p className="text-sm text-zinc-300">{a.message}</p>
                    {a.action && (
                      <p className="text-xs text-zinc-400 mt-2 flex items-start gap-1.5">
                        <span className="text-zinc-500">→</span>
                        <span>{a.action}</span>
                      </p>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}

function Counter({ color, value, label }: { color: string; value: number; label: string }) {
  const colors: Record<string, string> = {
    red:     "text-red-400 border-red-500/30 bg-red-500/10",
    amber:   "text-amber-300 border-amber-500/30 bg-amber-500/10",
    emerald: "text-emerald-300 border-emerald-500/30 bg-emerald-500/10",
  };
  return (
    <span className={`inline-flex items-center gap-1.5 px-2 py-1 rounded border ${colors[color]}`}>
      <span className="font-mono font-semibold">{value}</span>
      <span className="text-zinc-500">{label}</span>
    </span>
  );
}
